// Grove Park Investor Portal — Embedded Data
// 37 properties, 147 unique investors
// Design: Command Center — light mode, blue-700 accent, Inter font

export interface Investor {
  name: string;
  pct_capital: number | null;
  email: string;
  notes?: string;
}

export interface Property {
  id: string;
  name: string;
  entity_name: string;
  entity_ein: string;
  investors: Investor[];
  isGrovePark?: boolean;
}

export const PROPERTIES: Property[] = [
  {
    id: "ara",
    name: "ARA",
    entity_name: "Apartment Rental Assistance II, Inc",
    entity_ein: "95-4494515",
    investors: [
      { name: "Marc Menowitz", pct_capital: 100, email: "" },
    ],
  },
  {
    id: "anaheim-gardens",
    name: "Anaheim Gardens",
    entity_name: "Anaheim Gardens Housing, LP",
    entity_ein: "95-4494515",
    investors: [
      { name: "MT Anaheim Gardens, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com", notes: "formerly Mowgli, LLC" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
    ],
  },
  {
    id: "arbor-crest",
    name: "Arbor Crest",
    entity_name: "Arbor Crest Housing, LP",
    entity_ein: "82-3335281",
    investors: [
      { name: "MT Arbor Crest, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.85, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.85, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.32, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 1.06, email: "blake@apartmentcorp.com" },
      { name: "Jonathan McLelland", pct_capital: 0.79, email: "jonathan@menowitz.com" },
    ],
  },
  {
    id: "boca-ciega",
    name: "Boca Ciega",
    entity_name: "Boca Ciega Partners TC, LP",
    entity_ein: "65-0788082",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 100, email: "" },
    ],
  },
  {
    id: "breckenridge-village",
    name: "Breckenridge Village",
    entity_name: "Breckenridge Housing, LLC",
    entity_ein: "82-2540671",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 100, email: "" },
    ],
  },
  {
    id: "colonial-estates",
    name: "Colonial Estates",
    entity_name: "Thibodaux Housing, LP",
    entity_ein: "72-1479684",
    investors: [
      { name: "MT Colonial Estates, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.85, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.85, email: "mark@springprop.com" },
    ],
  },
  {
    id: "columbia-village",
    name: "Columbia Village",
    entity_name: "Oak Hills Housing, LP",
    entity_ein: "72-1430285",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 100, email: "" },
    ],
  },
  {
    id: "forrest-view",
    name: "Forrest View",
    entity_name: "Oak Hills Housing, LP",
    entity_ein: "72-1430285",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 100, email: "" },
    ],
  },
  {
    id: "oak-hills",
    name: "Oak Hills",
    entity_name: "Oak Hills Housing, LP",
    entity_ein: "72-1430285",
    investors: [
      { name: "MT Oak Hills, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.85, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.85, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.32, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 1.06, email: "blake@apartmentcorp.com" },
    ],
  },
  {
    id: "cumberland-apts",
    name: "Cumberland Apts",
    entity_name: "Cumberland Apartments, LP",
    entity_ein: "72-1430285",
    investors: [
      { name: "MT Cumberland, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.85, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.85, email: "mark@springprop.com" },
      { name: "Blake Livergood", pct_capital: 1.06, email: "blake@apartmentcorp.com" },
    ],
  },
  {
    id: "fairfax-senior-apts",
    name: "Fairfax Senior Apts",
    entity_name: "Fairfax Genesee Partners & Assoc LP",
    entity_ein: "95-4473550",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 80, email: "" },
      { name: "Rachel Huberman", pct_capital: 15, email: "rachaelhuberman406gmailcom@yahoo.com" },
      { name: "FM Fairfax LLC", pct_capital: 5, email: "" },
      { name: "Ira Menowitz", pct_capital: null, email: "" },
      { name: "Fred Menowitz", pct_capital: null, email: "" },
    ],
  },
  {
    id: "gates-on-manhattan",
    name: "Gates on Manhattan",
    entity_name: "Gates on Manhattan, LP",
    entity_ein: "47-3516090",
    investors: [
      { name: "MT Gates on Manhattan, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 14.44, email: "" },
      { name: "One Tree LLC", pct_capital: 14.44, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 11.02, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 7.01, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 1.6, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 1.6, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 1.6, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.4, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.4, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.0, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 0.8, email: "blake@apartmentcorp.com" },
      { name: "Jonathan McLelland", pct_capital: 0.6, email: "jonathan@menowitz.com" },
      { name: "Rick Realty Investments", pct_capital: 15, email: "" },
      { name: "Frederick Menowitz", pct_capital: 15, email: "" },
      { name: "Susan Menowitz", pct_capital: 10, email: "" },
      { name: "Todd Menowitz", pct_capital: 10, email: "" },
    ],
  },
  {
    id: "grace-townhomes",
    name: "Grace Townhomes",
    entity_name: "Grace Townhomes Housing, LLC",
    entity_ein: "82-3335281",
    investors: [
      { name: "MT Grace Townhomes, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.85, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.85, email: "mark@springprop.com" },
    ],
  },
  {
    id: "granite-ridge",
    name: "Granite Ridge",
    entity_name: "Granite Ridge Housing, LP",
    entity_ein: "47-3516090",
    investors: [
      { name: "MT Granite Ridge, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 14.44, email: "" },
      { name: "One Tree LLC", pct_capital: 14.44, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 11.02, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 7.01, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 1.6, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 1.6, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 1.6, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.4, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.4, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.0, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 0.8, email: "blake@apartmentcorp.com" },
      { name: "Jonathan McLelland", pct_capital: 0.6, email: "jonathan@menowitz.com" },
      { name: "Rick Realty Investments", pct_capital: 15, email: "" },
      { name: "Frederick Menowitz", pct_capital: 15, email: "" },
      { name: "Susan Menowitz", pct_capital: 10, email: "" },
      { name: "Todd Menowitz", pct_capital: 10, email: "" },
      { name: "Lisa Hamburger", pct_capital: 5, email: "" },
    ],
  },
  {
    id: "grove-park",
    name: "Grove Park",
    entity_name: "Grove Park Housing LP",
    entity_ein: "85-1924921",
    isGrovePark: true,
    investors: [
      { name: "Grove Park MT Investments LLC (MM 65%, TM 35%)", pct_capital: 99.99, email: "", notes: "Investors are under the MT, not the LP directly" },
      { name: "Crossroads Housing Dev Corp", pct_capital: 0.01, email: "" },
    ],
  },
  {
    id: "grove-park-housing-lp",
    name: "Grove Park Housing LP (MT Detail)",
    entity_name: "Grove Park Apts",
    entity_ein: "85-1924921",
    isGrovePark: true,
    investors: [
      { name: "Marc Menowitz (MM Shares 86.453%)", pct_capital: 86.453, email: "", notes: "MM Shares = 65% of MT" },
      { name: "Elle Menowitz (MM Shares 6.7873%)", pct_capital: 6.7873, email: "", notes: "MM Shares = 65% of MT" },
      { name: "Nicole Chriqui (MM Shares 2.2624%)", pct_capital: 2.2624, email: "", notes: "MM Shares = 65% of MT" },
      { name: "Kathy Chriqui (MM Shares 2.2624%)", pct_capital: 2.2624, email: "", notes: "MM Shares = 65% of MT" },
      { name: "Bill Greenberg (MM Shares 2.2624%)", pct_capital: 2.2624, email: "", notes: "MM Shares = 65% of MT" },
      { name: "Todd Menowitz (TM Shares 71.4286%)", pct_capital: 71.4286, email: "", notes: "TM Shares = 35% of MT" },
      { name: "FAM Descendants Trust (TM Shares 15.9664%)", pct_capital: 15.9664, email: "", notes: "TM Shares = 35% of MT" },
      { name: "Myles Menowitz (TM Shares 10.084%)", pct_capital: 10.084, email: "", notes: "TM Shares = 35% of MT" },
      { name: "Jon McLelland (TM Shares 2.521%)", pct_capital: 2.521, email: "", notes: "TM Shares = 35% of MT" },
    ],
  },
  {
    id: "holiday",
    name: "Holiday",
    entity_name: "Holiday Apartments Housing, LP",
    entity_ein: "72-1430285",
    investors: [
      { name: "MT Holiday, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.85, email: "evanngoldenberg@gmail.com" },
    ],
  },
  {
    id: "jefferson-arms",
    name: "Jefferson Arms",
    entity_name: "Jefferson Arms Apartments, LLC",
    entity_ein: "82-2540671",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 100, email: "" },
      { name: "Todd Menowitz", pct_capital: null, email: "" },
    ],
  },
  {
    id: "lexington-arms",
    name: "Lexington Arms",
    entity_name: "Lexington Housing, LLC",
    entity_ein: "82-3335281",
    investors: [
      { name: "MT Lexington, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.85, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.85, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.32, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 1.06, email: "blake@apartmentcorp.com" },
    ],
  },
  {
    id: "macedonia",
    name: "Macedonia",
    entity_name: "Macedonia Apartments LLC",
    entity_ein: "82-2540671",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 100, email: "" },
      { name: "Todd Menowitz", pct_capital: null, email: "" },
    ],
  },
  {
    id: "marrero-3",
    name: "Marrero 3",
    entity_name: "Marrero 3, LP",
    entity_ein: "72-1479684",
    investors: [
      { name: "MT Marrero, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.85, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.85, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.32, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 1.06, email: "blake@apartmentcorp.com" },
    ],
  },
  {
    id: "midtown-manor",
    name: "Midtown Manor",
    entity_name: "Midtown Manor Associates, LP",
    entity_ein: "95-4473550",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 80, email: "" },
      { name: "Rachel Huberman", pct_capital: 15, email: "rachaelhuberman406gmailcom@yahoo.com" },
      { name: "FM Midtown LLC", pct_capital: 5, email: "" },
    ],
  },
  {
    id: "new-wilmington-arms",
    name: "New Wilmington Arms",
    entity_name: "Wilmington Arms Housing, LP",
    entity_ein: "45-4345411",
    investors: [
      { name: "MT Property Investment, LLC", pct_capital: 19.999, email: "" },
      { name: "Rick Realty Investments Co LP", pct_capital: 12, email: "" },
      { name: "Frederick Menowitz", pct_capital: 12, email: "" },
      { name: "Susan Menowitz", pct_capital: 8, email: "" },
      { name: "Todd Menowitz", pct_capital: 8, email: "" },
      { name: "Lisa Hamburger", pct_capital: 4, email: "" },
      { name: "Rachel Huberman", pct_capital: 4, email: "rachaelhuberman406gmailcom@yahoo.com" },
      { name: "Marc Menowitz", pct_capital: 14.44, email: "" },
      { name: "One Tree LLC", pct_capital: 14.44, email: "timt@ltdevelopment.com" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 1.6, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 1.6, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 1.6, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.4, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.4, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.0, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 0.8, email: "blake@apartmentcorp.com" },
      { name: "Jonathan McLelland", pct_capital: 0.6, email: "jonathon@menowitz.com" },
    ],
  },
  {
    id: "opa-locka",
    name: "Opa Locka (135th St Apts)",
    entity_name: "Opa Locka Housing, LP",
    entity_ein: "65-0788082",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 80, email: "" },
      { name: "Rachel Huberman", pct_capital: 10, email: "rachaelhuberman406gmailcom@yahoo.com" },
      { name: "FM Opa Locka LLC", pct_capital: 5, email: "" },
      { name: "Ira Menowitz", pct_capital: null, email: "" },
      { name: "Fred Menowitz", pct_capital: null, email: "" },
      { name: "Todd Menowitz", pct_capital: 5, email: "" },
      { name: "Jonathan McLelland", pct_capital: null, email: "jonathan@menowitz.com" },
    ],
  },
  {
    id: "pacific-pointe",
    name: "Pacific Pointe",
    entity_name: "Pacific Pointe Housing, LP",
    entity_ein: "47-3516090",
    investors: [
      { name: "MT Pacific Pointe, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 14.44, email: "" },
      { name: "One Tree LLC", pct_capital: 14.44, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 11.02, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 7.01, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 1.6, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 1.6, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 1.6, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.4, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.4, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.0, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 0.8, email: "blake@apartmentcorp.com" },
      { name: "Jonathan McLelland", pct_capital: 0.6, email: "jonathan@menowitz.com" },
      { name: "Rick Realty Investments", pct_capital: 15, email: "" },
      { name: "Frederick Menowitz", pct_capital: 15, email: "" },
      { name: "Susan Menowitz", pct_capital: 10, email: "" },
      { name: "Todd Menowitz", pct_capital: 10, email: "" },
      { name: "Lisa Hamburger", pct_capital: 5, email: "" },
    ],
  },
  {
    id: "river-pointe",
    name: "River Pointe Apts",
    entity_name: "River Pointe Housing, LLC",
    entity_ein: "82-2540671",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 100, email: "" },
      { name: "Todd Menowitz", pct_capital: null, email: "" },
      { name: "Jonathan McLelland", pct_capital: null, email: "jonathan@menowitz.com" },
    ],
  },
  {
    id: "riverchase-apts",
    name: "Riverchase Apts",
    entity_name: "Riverchase Housing, LP",
    entity_ein: "72-1430285",
    investors: [
      { name: "MT Riverchase, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.85, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.85, email: "mark@springprop.com" },
    ],
  },
  {
    id: "ruby-diamond",
    name: "Ruby Diamond",
    entity_name: "Ruby Diamond Housing LP",
    entity_ein: "82-3335281",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 80, email: "" },
      { name: "Rachel Huberman", pct_capital: 15, email: "rachaelhuberman406gmailcom@yahoo.com" },
      { name: "FM Ruby Diamond LLC", pct_capital: 5, email: "" },
      { name: "Todd Menowitz", pct_capital: null, email: "" },
    ],
  },
  {
    id: "star-homes",
    name: "Star Homes",
    entity_name: "Star Homes I, LP",
    entity_ein: "72-1479684",
    investors: [
      { name: "MT Star Homes, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
    ],
  },
  {
    id: "silver-springs",
    name: "Silver Springs Terrace Apts",
    entity_name: "Silver Springs Housing, LP",
    entity_ein: "72-1479684",
    investors: [
      { name: "MT Silver Springs, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 2.11, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
    ],
  },
  {
    id: "st-charles-place",
    name: "St. Charles Place",
    entity_name: "St. Charles Housing, LP",
    entity_ein: "72-1479684",
    investors: [
      { name: "MT St. Charles, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 14.44, email: "" },
      { name: "One Tree LLC", pct_capital: 14.44, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 11.02, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 7.01, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 1.6, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 1.6, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 1.6, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.4, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.4, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.0, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 0.8, email: "blake@apartmentcorp.com" },
      { name: "Jonathan McLelland", pct_capital: 0.6, email: "jonathan@menowitz.com" },
      { name: "Rick Realty Investments", pct_capital: 15, email: "" },
      { name: "Frederick Menowitz", pct_capital: 15, email: "" },
    ],
  },
  {
    id: "urban-rehab",
    name: "Urban Rehab",
    entity_name: "Main South Central Associates, LP",
    entity_ein: "95-4494515",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 100, email: "" },
      { name: "Todd Menowitz", pct_capital: null, email: "" },
    ],
  },
  {
    id: "village-green",
    name: "Village Green Apts",
    entity_name: "Village Green Housing, LP",
    entity_ein: "47-3516090",
    investors: [
      { name: "MT Village Green, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 14.44, email: "" },
      { name: "One Tree LLC", pct_capital: 14.44, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 11.02, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 7.01, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 1.6, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 1.6, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 1.6, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.4, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.4, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.0, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 0.8, email: "blake@apartmentcorp.com" },
      { name: "Jonathan McLelland", pct_capital: 0.6, email: "jonathan@menowitz.com" },
      { name: "Rick Realty Investments", pct_capital: 15, email: "" },
      { name: "Frederick Menowitz", pct_capital: 15, email: "" },
    ],
  },
  {
    id: "windsor-yorkshire",
    name: "Windsor / Yorkshire",
    entity_name: "Windsor Housing, LP",
    entity_ein: "47-3516090",
    investors: [
      { name: "MT Windsor, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 14.44, email: "" },
      { name: "One Tree LLC", pct_capital: 14.44, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 11.02, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 7.01, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 1.6, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 1.6, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 1.6, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.4, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.4, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.0, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 0.8, email: "blake@apartmentcorp.com" },
      { name: "Jonathan McLelland", pct_capital: 0.6, email: "jonathan@menowitz.com" },
      { name: "Rick Realty Investments", pct_capital: 15, email: "" },
      { name: "Frederick Menowitz", pct_capital: 15, email: "" },
      { name: "Susan Menowitz", pct_capital: 10, email: "" },
      { name: "Todd Menowitz", pct_capital: 10, email: "" },
    ],
  },
  {
    id: "thomasville-church-homes",
    name: "Thomasville Church Homes",
    entity_name: "Thomasville Church Housing LLC",
    entity_ein: "82-2540671",
    investors: [
      { name: "Marc & Ellie Menowitz Family Trust", pct_capital: 80, email: "" },
      { name: "Rachel Huberman", pct_capital: 15, email: "rachaelhuberman406gmailcom@yahoo.com" },
      { name: "FM Thomasville LLC", pct_capital: 5, email: "" },
      { name: "Ira Menowitz", pct_capital: null, email: "" },
      { name: "Fred Menowitz", pct_capital: null, email: "" },
      { name: "Todd Menowitz", pct_capital: null, email: "" },
    ],
  },
  {
    id: "coral-village",
    name: "Coral Village Apts",
    entity_name: "Coral Village Housing LP",
    entity_ein: "65-0788082",
    investors: [
      { name: "MT Coral Village, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 14.44, email: "" },
      { name: "One Tree LLC", pct_capital: 14.44, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 11.02, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 7.01, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 1.6, email: "akaushansky@gmail.com" },
      { name: "Carlos Iturriaga", pct_capital: 1.6, email: "citurriaga@rebelbases.com" },
      { name: "Guru Thapar", pct_capital: 1.6, email: "guru@212pier.com" },
      { name: "Evan Goldenberg", pct_capital: 1.4, email: "evanngoldenberg@gmail.com" },
      { name: "Mark Colman", pct_capital: 1.4, email: "mark@springprop.com" },
      { name: "Apolonia Darner", pct_capital: 1.0, email: "nonee@apartmentcorp.com" },
      { name: "Blake Livergood", pct_capital: 0.8, email: "blake@apartmentcorp.com" },
      { name: "Jonathan McLelland", pct_capital: 0.6, email: "jonathan@menowitz.com" },
      { name: "Rick Realty Investments", pct_capital: 15, email: "" },
      { name: "Frederick Menowitz", pct_capital: 15, email: "" },
      { name: "Susan Menowitz", pct_capital: 10, email: "" },
      { name: "Todd Menowitz", pct_capital: 10, email: "" },
    ],
  },
  {
    id: "river-garden-estates",
    name: "River Garden Estates",
    entity_name: "River Garden Estates Housing LP",
    entity_ein: "82-3335281",
    investors: [
      { name: "MT River Garden, LLC (75% Marc, 25% Todd)", pct_capital: 25, email: "" },
      { name: "Marc Menowitz", pct_capital: 19.01, email: "" },
      { name: "One Tree LLC", pct_capital: 19.01, email: "timt@ltdevelopment.com" },
      { name: "Todd Menowitz", pct_capital: 14.52, email: "" },
      { name: "Bingham, LP (Fred Turner)", pct_capital: 9.24, email: "kaitlynturner28@gmail.com", notes: "Fred is deceased. Distributions/K1s go to daughter Kaitlyn" },
      { name: "Mowgli Sequoia LLC (Alexander Kaushansky)", pct_capital: 2.11, email: "akaushansky@gmail.com" },
      { name: "Guru Thapar", pct_capital: 2.11, email: "guru@212pier.com" },
    ],
  },
];

// Build investor cross-reference index
export interface InvestorEntry {
  name: string;
  properties: { propertyName: string; propertyId: string; entityName: string; pct_capital: number | null; email: string }[];
}

export function buildInvestorIndex(): InvestorEntry[] {
  const map = new Map<string, InvestorEntry>();
  for (const prop of PROPERTIES) {
    for (const inv of prop.investors) {
      const key = inv.name.toLowerCase().trim();
      if (!map.has(key)) {
        map.set(key, { name: inv.name, properties: [] });
      }
      map.get(key)!.properties.push({
        propertyName: prop.name,
        propertyId: prop.id,
        entityName: prop.entity_name,
        pct_capital: inv.pct_capital,
        email: inv.email,
      });
    }
  }
  return Array.from(map.values()).sort((a, b) => a.name.localeCompare(b.name));
}
